name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ContinuousIntegration.sln

    - name: Build
      run: dotnet build ContinuousIntegration.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ContinuousIntegration.sln --no-build --verbosity normal
